// Fix: Provide content for constants.ts to define data structures and translations used throughout the application.
import type { Role, User, Room, Booking } from './types';

export const ROLES: Role[] = [
    { id: '1', name: 'Admin', permissions: ['manageRooms', 'manageSettings', 'viewAllBookings'] },
    { id: '2', name: 'Manager', permissions: ['manageRooms', 'viewAllBookings'] },
    { id: '3', name: 'User', permissions: [] },
];

export const USERS: User[] = [
    { id: '1', name: 'Alex Johnson', email: 'alex.j@example.com', roleId: '1' },
    { id: '2', name: 'Maria Garcia', email: 'maria.g@example.com', roleId: '2' },
    { id: '3', name: 'Sam Wilson', email: 'sam.w@example.com', roleId: '3' },
];

export const ROOMS: Room[] = [
    { id: '1', name: 'Conference Room A', capacity: 10, amenities: ['Projector', 'Whiteboard', 'Video Conferencing'], photoUrl: 'https://images.unsplash.com/photo-1590650153855-d9e808231d40?q=80&w=2070&auto=format&fit=crop' },
    { id: '2', name: 'Focus Room B', capacity: 4, amenities: ['Whiteboard'], photoUrl: 'https://images.unsplash.com/photo-1617791160536-595cfb5c4658?q=80&w=1964&auto=format&fit=crop' },
    { id: '3', name: 'Training Room C', capacity: 25, amenities: ['Projector', 'Sound System'], photoUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1932&auto=format&fit=crop' },
];

const now = new Date();
export const BOOKINGS: Booking[] = [
    { 
        id: '1', 
        userId: '3', 
        roomId: '2', 
        title: 'Team Sync', 
        startTime: new Date(now.getFullYear(), now.getMonth(), now.getDate(), now.getHours() + 1, 0), 
        endTime: new Date(now.getFullYear(), now.getMonth(), now.getDate(), now.getHours() + 2, 0) 
    },
    { 
        id: '2', 
        userId: '2', 
        roomId: '1', 
        title: 'Client Presentation', 
        startTime: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 14, 0), 
        endTime: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 15, 30) 
    },
    {
        id: '3',
        userId: '1',
        roomId: '3',
        title: 'All-Hands Meeting',
        startTime: new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1, 10, 0),
        endTime: new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1, 11, 0),
    }
];

export const TRANSLATIONS = {
    en: {
        appName: 'SyncSpace',
        welcome: 'Welcome back!',
        loginPrompt: 'Please sign in to your account.',
        username: 'Username',
        password: 'Password',
        email: 'Email',
        login: 'Login',
        loginError: 'Invalid username or password.',
        dashboard: 'Dashboard',
        calendar: 'Calendar',
        myBookings: 'My Bookings',
        myBookingsMessage: 'Here you can see all your bookings, past and present.',
        noBookings: 'You have no bookings.',
        profile: 'Profile',
        viewProfile: 'View Profile',
        myUpcomingBookings: 'My Upcoming Bookings',
        myStats: 'My Stats',
        totalBookings: 'Total Bookings',
        profileMessage: 'This is your personal space. View your upcoming meetings and manage your profile details here.',
        rooms: 'Rooms',
        settings: 'Settings',
        logout: 'Logout',
        upcomingBookings: 'Upcoming Bookings',
        noUpcomingBookings: 'No upcoming bookings.',
        bookARoom: 'Book a Room',
        viewList: 'List',
        viewCalendar: 'Calendar',
        deleteBookingConfirm: 'Are you sure you want to delete this booking?',
        manageRooms: 'Manage Rooms',
        addRoom: 'Add Room',
        deleteRoomConfirm: 'Are you sure you want to delete this room? All associated bookings will be removed.',
        roomStatusBusyUntil: 'Busy until {time}',
        roomStatusUpcomingAt: 'Upcoming meeting at {time}',
        roomStatusAvailableNext: 'Available until next meeting at {time}',
        roomStatusAvailableAllDay: 'Available all day',
        capacity: 'Capacity',
        amenities: 'Amenities',
        settingsTitle: 'Settings',
        userManagement: 'User Management',
        addUser: 'Add User',
        roleManagement: 'Role Management',
        permissions: 'Permissions',
        accessDenied: 'Access Denied',
        editRoom: 'Edit Room',
        roomName: 'Room Name',
        photo: 'Photo',
        uploadPhoto: 'Upload Photo',
        save: 'Save',
        cancel: 'Cancel',
        role: 'Role',
        newBooking: 'New Booking',
        noBookingsForDate: 'No bookings for this day.',
        previousMonth: 'Previous',
        nextMonth: 'Next',
        addBooking: 'Add Booking',
        editBooking: 'Edit Booking',
        title: 'Title',
        date: 'Date',
        startTime: 'Start Time',
        endTime: 'End Time',
        selectRoom: 'Select a room',
        dailySchedule: 'Daily Schedule',
        bookingConflict: 'This time slot is already booked for the selected room.',
        bookingAdded: 'Booking successfully added!',
        bookingUpdated: 'Booking successfully updated!',
        bookingDeleted: 'Booking successfully deleted!',
        roomAdded: 'Room successfully added!',
        roomUpdated: 'Room successfully updated!',
        roomDeleted: 'Room successfully deleted!',
        userAdded: 'User successfully added!',
        userDeleted: 'User successfully deleted!',
        roleUpdated: 'User role updated!',
        permissionsUpdated: 'Role permissions updated!',
        delete: 'Delete',
        deleteBookingTitle: 'Delete Booking',
        deleteRoomTitle: 'Delete Room',
        deleteUserTitle: 'Delete User',
        deleteUserConfirm: 'Are you sure you want to delete this user? All associated bookings will be removed.',
    },
    ar: {
        appName: 'سينك سبيس',
        welcome: 'مرحبا بعودتك!',
        loginPrompt: 'الرجاء تسجيل الدخول إلى حسابك.',
        username: 'اسم المستخدم',
        password: 'كلمة المرور',
        email: 'البريد الإلكتروني',
        login: 'تسجيل الدخول',
        loginError: 'اسم المستخدم أو كلمة المرور غير صالحة.',
        dashboard: 'لوحة التحكم',
        calendar: 'التقويم',
        myBookings: 'حجوزاتي',
        myBookingsMessage: 'هنا يمكنك رؤية جميع حجوزاتك، السابقة والحالية.',
        noBookings: 'ليس لديك أي حجوزات.',
        profile: 'الملف الشخصي',
        viewProfile: 'عرض الملف الشخصي',
        myUpcomingBookings: 'حجوزاتي القادمة',
        myStats: 'إحصائياتي',
        totalBookings: 'إجمالي الحجوزات',
        profileMessage: 'هذه هي مساحتك الشخصية. اعرض اجتماعاتك القادمة وأدر تفاصيل ملفك الشخصي هنا.',
        rooms: 'الغرف',
        settings: 'الإعدادات',
        logout: 'تسجيل الخروج',
        upcomingBookings: 'الحجوزات القادمة',
        noUpcomingBookings: 'لا توجد حجوزات قادمة.',
        bookARoom: 'احجز غرفة',
        viewList: 'قائمة',
        viewCalendar: 'تقويم',
        deleteBookingConfirm: 'هل أنت متأكد أنك تريد حذف هذا الحجز؟',
        manageRooms: 'إدارة الغرف',
        addRoom: 'أضف غرفة',
        deleteRoomConfirm: 'هل أنت متأكد أنك تريد حذف هذه الغرفة؟ ستتم إزالة جميع الحجوزات المرتبطة.',
        roomStatusBusyUntil: 'مشغولة حتى {time}',
        roomStatusUpcomingAt: 'اجتماع قادم الساعة {time}',
        roomStatusAvailableNext: 'متاحة حتى الاجتماع التالي الساعة {time}',
        roomStatusAvailableAllDay: 'متاحة طوال اليوم',
        capacity: 'السعة',
        amenities: 'وسائل الراحة',
        settingsTitle: 'الإعدادات',
        userManagement: 'إدارة المستخدمين',
        addUser: 'أضف مستخدم',
        roleManagement: 'إدارة الأدوار',
        permissions: 'الأذونات',
        accessDenied: 'الوصول مرفوض',
        editRoom: 'تعديل الغرفة',
        roomName: 'اسم الغرفة',
        photo: 'الصورة',
        uploadPhoto: 'تحميل صورة',
        save: 'حفظ',
        cancel: 'إلغاء',
        role: 'الدور',
        newBooking: 'حجز جديد',
        noBookingsForDate: 'لا توجد حجوزات لهذا اليوم.',
        previousMonth: 'السابق',
        nextMonth: 'التالي',
        addBooking: 'إضافة حجز',
        editBooking: 'تعديل الحجز',
        title: 'العنوان',
        date: 'التاريخ',
        startTime: 'وقت البدء',
        endTime: 'وقت الانتهاء',
        selectRoom: 'اختر غرفة',
        dailySchedule: 'الجدول اليومي',
        bookingConflict: 'هذه الفترة الزمنية محجوزة بالفعل للغرفة المختارة.',
        bookingAdded: 'تمت إضافة الحجز بنجاح!',
        bookingUpdated: 'تم تحديث الحجز بنجاح!',
        bookingDeleted: 'تم حذف الحجز بنجاح!',
        roomAdded: 'تمت إضافة الغرفة بنجاح!',
        roomUpdated: 'تم تحديث الغرفة بنجاح!',
        roomDeleted: 'تم حذف الغرفة بنجاح!',
        userAdded: 'تمت إضافة المستخدم بنجاح!',
        userDeleted: 'تم حذف المستخدم بنجاح!',
        roleUpdated: 'تم تحديث دور المستخدم!',
        permissionsUpdated: 'تم تحديث أذونات الدور!',
        delete: 'حذف',
        deleteBookingTitle: 'حذف الحجز',
        deleteRoomTitle: 'حذف الغرفة',
        deleteUserTitle: 'حذف المستخدم',
        deleteUserConfirm: 'هل أنت متأكد أنك تريد حذف هذا المستخدم؟ ستتم إزالة جميع الحجوزات المرتبطة.',
    },
};